name: client
description: Client part of the async_redux_tic_tac_toe project (multiplayer game made using async_redux package and Firebase).
author: André Lúcio <arlucio.dev@gmail.com>
version: 1.0.0+1
homepage: https://github.com/arlucio/async_redux_tic_tac_toe

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  business:
    path: ../business/

  flutter_spinkit: ^5.0.0
  align_positioned: ^2.0.1
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  font_awesome_flutter: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hash_logo.png

  fonts:
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/bungee_shade/BungeeShade-Regular.ttf
