name: client
description: Client part of the async_redux_tic_tac_toe project (multiplayer game made using async_redux package and Firebase).
author: André Lúcio <arlucio.dev@gmail.com>
version: 1.0.0+1
homepage: https://github.com/arlucio/async_redux_tic_tac_toe

dependencies:
  flutter:
    sdk: flutter
  business:
    path: ../business/

  flutter_spinkit: ^3.1.0
  align_positioned: ^1.0.8
  path_provider: ^0.4.1
  url_launcher: ^5.1.2
  font_awesome_flutter: ^8.5.0

#  flutter_launcher_icons: "^0.7.2"
#
#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/hash_logo.png"
#  adaptive_icon_background: "#ffffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/hash_logo.png

  fonts:
    - family: BungeeShade
      fonts:
        - asset: assets/fonts/bungee_shade/BungeeShade-Regular.ttf
