name: business
description: Business part of the async_redux_tic_tac_toe project (multiplayer game made using async_redux package and Firebase).
author: André Lúcio <arlucio.dev@gmail.com>
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

#####IMPORTANT: Remember to always 'Packages get' on client when you make changes on this file.

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^0.4.0+8
  firebase_database: ^3.0.5
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9

  async_redux: ^1.3.9
  http: ^0.12.0+2
  uuid: 2.0.1
  rxdart: ^0.22.0
  faker: ^1.1.1
  get_it: ^2.0.3
#  built_value: 6.7.0
#  built_collection: 4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1+1
#  build_runner: 1.6.5
#  built_value_generator: 6.7.0


