name: business
description: Business part of the async_redux_tic_tac_toe project (multiplayer game made using async_redux package and Firebase).
author: André Lúcio <arlucio.dev@gmail.com>
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.0.4
  firebase_database: ^6.1.2
  firebase_auth: ^1.0.4
  cloud_firestore: ^1.0.6

  async_redux: ^9.0.7
  http: ^0.13.1
  uuid: 3.0.4
  rxdart: ^0.26.0
  faker: ^1.3.0
  get_it: ^6.1.1
  built_value: 8.0.4
  built_collection: 5.0.0



